# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages


os:
  - linux
  - osx

r:
  - 3.4
  - release
  - 3.5


after_success:
  - Rscript -e 'covr::codecov(type="all")'
